from core.mocker import *

# 默认是在ARM64环境下！！！
ARM_DEFAULT_LATIN = LATIN_LITTLE # 根据机器定义
ARM_DEFAULT_MASK = INT_Mask # 根据机器定义
ARM_DEFAULT_MASK_SIZE = 64 # 64位

ARM_DEFAULT_MEMORY_SIZE = MEMORY_SIZE
ARM_DEFAULT_REGISTER_MODE = REGISTER_MODE_W #

ARM_DEFAULT_MEMORY_MODE = REGISTER_MODE_X # 以64位存储
